version: '3.8'
volumes:
  esdata:

services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50

  fastapi:
    container_name: fastapi
    build: ./
    restart: always
    environment:
      - ELASTIC_HOST=elasticsearch
      - REDIS_HOST=redis
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: sh -c "poetry run python3 etl/pipeline.py && poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000"
